//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public string Cat_ID { get; set; }
        public string Cat_Name { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
