//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string pro_id { get; set; }
        public string pro_name { get; set; }
        public int quantity { get; set; }
        public long pro_price { get; set; }
        public string pro_image { get; set; }
        public string cat_id { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
